server:
  port: 10086

# redis配置
redisson:
  #  address: redis://192.168.1.136:6379
  address: redis://127.0.0.1:6379
  database: 0
#  password: foobared

# 数据源
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
